# Generated by Django 5.1.4 on 2025-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('image', models.URLField(verbose_name='Картинка')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Поддержка LTE')),
            ],
        ),
    ]
